### ISSUE TITLE
Add option to re-enable rss feeds

### ISSUE THREAD

**Issue by cjg89** [UCF/Colleges-Theme#38]
Currently, RSS feeds are disabled within the feed to prevent exposure of unneeded content:
https://github.com/UCF/Colleges-Theme/blob/af9b18c565c558dedf43ea57f7d929b3cce89c84/includes/config.php#L412

However, some sites may need to utilize RSS feeds in particular--we should add a customizer option that enables/disables this 404 redirect for feeds.

**Comment by cadieb** [comment]
Resolved in #39.
